apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
data:
  authPluginConfig.json: {{ .Values.authPluginConfig | mustToRawJson | quote }}
  allowedExternalRedirectDomains.json: {{ .Values.global.authPluginAllowedExternalRedirectDomains | mustToRawJson | quote }}
